### ISSUE TITLE
Will `tesspy` support `GeoSeries`?

### ISSUE THREAD

**Issue by Zeroto521** [siavash-saki/tesspy#3]
Now `tesspy` only support `GeoDataFrame`.
Most of all `tesspy` functions could accept both `GeoDataFrame` and `GeoSeries`.
And running without any error. Except `count_poi` method, `sjoin` require `GeoDataFrame`.

**Comment by siavash-saki** [comment]
@Zeroto521 Thanks for the question. As you pointed out, the `Tessellation` object requires a `GeoDataFrame` for now. But we would consider supporting `GeoSeries` in the next version.
