### ISSUE TITLE
Notebooks installation returns errors due to the wrong syntax in requirement.txt

### ISSUE THREAD

**Issue by BenjMy** [siavash-saki/tesspy#37]
xref https://github.com/openjournals/joss-reviews/issues/4620

During the installation of the [requirements_tutorials.txt](https://github.com/siavash-saki/tesspy/blob/main/Examples/requirements_tutorials.txt) file using `pip install -r requirements_tutorials.txt`: 

- an error is raised due to the wrong operator specifying geopandas version
- h3-py is not existing (I assume this should be replaced by h3)

You should also check this also for the tutorials_env.yaml
By the way there is a typo in the filename, replace tutiruals_env.yaml by tutorials_env

**Comment by siavash-saki** [comment]
The dependency is called "h3" on pypi and "h3-py" in conda-forge. The `requirements_tutorials.txt` is supposed to be used for installing the dependencies using conda.

You can actually create a new conda env with channel set to `conda-forge` and install the requirements using conda as follows:

`$ conda install -c conda-forge --file requirements_tutorials.txt`

That should actually work. (I just tested it again). And the operator specifying the geopandas version doesn't raise any error in this method. 

I will add this instruction also the the example notebook.

Btw, thanks for mentioning the typo in the file name. I'll correct it.
