### ISSUE TITLE
Tesselating a set of points

### ISSUE THREAD

**Issue by ysig** [siavash-saki/tesspy#52]
Hi,

I have a set of points and I'm trying to use this library to tessellate them to adaptive (in terms of how many points are per cell) cells.

My geodataframe looks like this:

![image](https://user-images.githubusercontent.com/28439529/191135670-d0dbcb3c-5ac5-4997-b67a-18ed9d83521a.png)

and I run:

`df = Tessellation(gdf)`

I get the following error:

![image](https://user-images.githubusercontent.com/28439529/191135750-59c60cb7-93db-4920-ab9f-562b88461529.png)

How can I do this with this library?

**Comment by JoHamann** [comment]
Hello, 

the idea behind this library is to tessellate the (geographical) space. With the adaptive method, the space is divided e.g. by points of interest (POI). So the input for this method is the underlying space (to be tessellated) and POI categories. 

The Tessellation() object requires a string (e.g. a city/country etc.) or a gdf with an entry, a polygon, to be tessellated. 
Feel free to look at the examples to get a better idea how the library works. [Examples](https://github.com/siavash-saki/tesspy/blob/main/Examples/02_Tessllating_Different_Cities.ipynb)

If you could specify your input or the goal, we can maybe help you.
