### ISSUE TITLE
[JOSS] Supported Python versions?

### ISSUE THREAD

**Issue by jGaboardi** [siavash-saki/tesspy#9]
xref #6 openjournals/joss-reviews#4620

https://github.com/siavash-saki/tesspy/blob/d3e662dfafd887f9ba9bc612d73688515a666af8/setup.py#L23-L28

Currently there are no supported Python versions in `setup.py`. Ideally, this should match the Python version that are being tested against in CI. As an example see [`setup.py` in `pysal/momepy`]().

**Comment by siavash-saki** [comment]
We have this in the [`setup.py`:](https://github.com/siavash-saki/tesspy/blob/d070497850e623a7968d7c07f7c6353bc8e0bd45/setup.py)

https://github.com/siavash-saki/tesspy/blob/d070497850e623a7968d7c07f7c6353bc8e0bd45/setup.py#L30

I looked at the classifiers in [`momepy/setup.py`:](https://github.com/pysal/momepy/blob/7344e77cda22329a62131ea99a8ffc7ffc6a1b94/setup.py#L36-L42) It's actually the same as ours. I didn't quite understand what to change. Do you mean to add something like these to classifiers?

```
"Programming Language :: Python :: 3.7",
"Programming Language :: Python :: 3.8",
"Programming Language :: Python :: 3.9",
"Programming Language :: Python :: 3.10"
```

**Comment by jGaboardi** [comment]
Yes, exactly!
